<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-3">
           <?php print render($page['footer_first']); ?>
      </div><!-- /.col -->
      <div class="col-sm-6 col-md-3">
        <h2>Ven a Katakrak</h2>
        <ul class="list-unstyled">
          <li class="list-item">C/ Mayor 54, Pamplona-Iruñea</li>
          <li class="list-item">31001 Navarra-Nafarroa</li>
          <li class="list-item">
            <a class="" href="https://xabiangos.com/katakrak-bs/index.html#">Localízanos</a>
          </li>
        </ul>

        <ul class="list-unstyled">
          <li class="list-style">Abierto de lunes a sábado:</li>
          <li class="list-item"> <span class="strong">Librería: </span> 10:00-20:30</li>
          <li class="list-item"><span class="strong">Cantina: </span>  L,M,M 10:00-22:00 | J,V,S 10:00-01:00</li>
        </ul>

       
        <ul class="list-unstyled">
          <li class="list-item">Escríbenos a:  <a href="mailto:info@katakrak.net">info@katakrak.net</a></li>
          <li class="list-item">O llámanos al <a href="tel:+34948225520">948225520</a> </li>
          
        </ul>

      </div><!-- /.col -->
      <div class="col-sm-6 col-md-3">
        <h2>Social</h2>
        <ul class="list-unstyled list-social mt-3">
          <li class="list-item mb-3">
            <a class="d-flex" href="https://www.facebook.com/katakrak54" target="_blank" title="Facebook">
              <i class="fab fa-facebook-f" aria-hidden="true"></i>
              <span>Facebook</span>
            </a>
          </li>
          <li class="list-item mb-3">
            <a class="d-flex" href="http://twitter.com/katakrak54" target="_blank" title="Twitter">
              <i class="fab fa-twitter" aria-hidden="true"></i>
              <span>Twitter</span>
            </a>
          </li>
          <li class="list-item mb-3">
            <a class="d-flex" href="https://www.instagram.com/katakrak54/" target="_blank" title="Instagram">
              <i class="fab fa-instagram" aria-hidden="true"></i>
              <span>Instagram</span>
            </a>
          </li>
          <li class="list-item mb-3">
            <a class="d-flex" href="http://soundcloud.com/katakrak54" target="_blank" title="Soundcloud">
              <i class="fab fa-soundcloud" aria-hidden="true"></i>
              <span>Soundcloud</span>
            </a>
          </li>
          <li class="list-item mb-3">
            <a class="d-flex" href="https://katakrak.net/cas/events/feed" target="_blank" title="Feed">
              <i class="fas fa-rss" aria-hidden="true"></i>
              <span>RSS eventos feed</span>
            </a>
          </li>
        </ul>
        
          
      </div><!-- /.col -->
      <div class="col-sm-6 col-md-3">
        <h2>Suscríbete a la Newsletter</h2>
        <p>Prometemos no darte la chapa más de lo necesario</p>
        <form>
          <div class="form-group">
            <input type="text" class="form-control form-control-sm" id="formGroupExampleInput" placeholder="Nombre" focus="">
          </div>
          <div class="form-group">
            <input type="text" class="form-control form-control-sm" id="formGroupExampleInput" placeholder="Apellidos">
          </div>
          <div class="form-group">
            <input type="mail" class="form-control form-control-sm" id="formGroupExampleInput" placeholder="Email">
          </div>
          <button class="btn btn-primary d-block">Suscribirme</button>
        </form>
        
      </div><!-- /.col -->

    </div><!-- /.row -->
  </div>
</footer>