<?php
/**
 * @file
 * Code for the Katakrak blog feature.
 */

include_once 'katakrak_blog.features.inc';

function katakrak_blog_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'blog' && $view_mode == 'full') {
    global $language;
    if ($node->content['field_blog_eventos']){
      $header = array(
        t('Title'),
        t('Date'),
      );
      $table = array();
      foreach ($node->content['field_blog_eventos']['#items'] as $rel) { 
        $event = $rel['node'];
        if ($event->tnid) {
          $translations = translation_node_get_translations($event->tnid);
          $event = node_load($translations[$language->language]->nid);
        }
        $table[] = array(
          l($event->title, 'node/'.$event->nid),
          format_date($event->field_event_date['und'][0]['value'], 'custom', 'd/m/Y - H:i')
        );
      }
      $node->event_table = theme('table', array('header' => $header, 'rows' => $table, 'caption' => t('Events'), 'attributes' => array('class' => array('table'))));
    }
  }
}