<?php
/**
 * @file
 * Code for the Katakrak blog feature.
 */

include_once 'katakrak_blog.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function katakrak_blog_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_block_info().
 */
function katakrak_blog_block_info() {
  $blocks = array();
  $blocks['katakrak_blog_search'] = array(
    'info' => t('Bloque búsqueda blogs'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['katakrak_blog_nav_secundary'] = array(
    'info' => t('Bloque de navegación secundario de blog'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function katakrak_blog_block_view($delta) {
  switch($delta) {
    case 'katakrak_blog_search':
      $form = drupal_get_form('katakrak_blog_search_form');
      $block['content'] = theme('katakrak_search_block', array('form' => $form));
      break;
    case 'katakrak_blog_nav_secundary':
      $links = array(
        l(t('Todos los blogs'), 'blog'),
        l(t('Cultura'),'taxonomy/term/42225'),
        l(t('Medios'),'taxonomy/term/41179'),
        l(t('Librería'),'taxonomy/term/40849'),
        l(t('Cocina'), 'taxonomy/term/40727')
      );
      $block['content'] = theme('katakrak_nav_secundary', array('links' => $links));
      break;
  }
  return $block;
}
 

/**
 * 
 * @param type $form
 * @param type $form_state
 * @return 
 */
function katakrak_blog_search_form($form, &$form_state) {
  
  $query = explode('/', current_path());
  
  $form['search_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Nombre'),
    '#title_display' => 'invisible',
    '#required' => TRUE,
    '#attributes' => array(
      'placeholder' => t('Buscar artículos'),
      'class' => array('mr-1'),
    ),
    '#theme_wrappers' => array(),
  );
  if (count($query) == 3 AND $query[0] != 'buscar')
    $form['search_term']['#attributes']['placeholder'] = t('Buscar artículos');
  else
    $form['search_term']['#attributes']['value'] = $query[2];
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '<i class="fas fa-search"></i> '.t('Buscar'),
    '#attributes' => array(
      'class' => array('btn btn-secondary'),
    )
  );
  $form['#theme'] = 'libro_search_home_form';
  return $form; 
}

function katakrak_blog_search_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'buscar/blogs/'.$form_state['values']['search_term'];
}