<?php

/**
 * @file
 * Code for the Katakrak Diska feature.
 */

include_once 'katakrak_diska.features.inc';



function disco_generar_boton_product($node, $sku = "diska") {

  $product = commerce_product_load_by_sku($sku);
  //dpm($product);
  $default_quantity = 1;
  $product_ids = array($product->product_id);
  // Build the line item we'll pass to the Add to form.
  $line_item = commerce_product_line_item_new($product, $default_quantity, 0, array(), 0);
  $line_item->data['context']['product_ids'] = $product_ids;
  $line_item->data['context']['add_to_cart_combine'] = 1;
  $line_item->commerce_product['und'][0]['product_id'] = $product->product_id;
  $line_item->commerce_display_path['und'][0] = array(
    'value' => 'node/'.$node->nid
  );

  // Generate a form ID for this add to cart form.
  $form_id = commerce_cart_add_to_cart_form_id($product_ids);
  $line_item->data['context']['display_path'] = current_path();
  // Build the Add to Cart form using the prepared values.
  $form = drupal_get_form($form_id, $line_item, 0, array());
  return drupal_render($form);

  }