<?php
/**
 * @file
 * Code for the Katakrak Sukaldea feature.
 */

include_once 'katakrak_sukaldea.features.inc';

function katakrak_sukaldea_node_load($nodes, $types) {
 
  foreach ($nodes as &$node) {
    if ($node->type == 'sukalde_errezeta') {
      $header = array(
        'produktua',
        'prezioa',
        'kopurua',
        'totala',
      );
      $table = array();
      $totala = 0;
      foreach($node->field_errezeta_osagai['und'] as $i => $osagai) {
        $osagai = field_collection_item_load($osagai['value']);
        $produktua = node_load($osagai->field_errezeta_produktua['und'][0]['target_id']);
        $table[$i][] = $produktua->title;
        $table[$i][] = $produktua->field_produktua_prezioa['und'][0]['value'];
        $table[$i][] = $osagai->field_errezeta_kopurua['und'][0]['value'];
        $linearen_totala = $osagai->field_errezeta_kopurua['und'][0]['value'] * $produktua->field_produktua_prezioa['und'][0]['value'];
        $table[$i][] = $linearen_totala;
        $totala += $linearen_totala;
      }
      $table[] = array(
          0 => 'Total',
          1 => '',
          2 => '',
          3 => $totala,
      );
      $node->produktu_taula = array('header' => $header, 'rows' => $table, 'attributes' => array('class' => array('table')));
      
      $node->prezio_gomendatua = ($totala * 3) / $node->field_errezeta_porzio_kopurua['und'][0]['value'];
      $node->razio_gomendatua = ($totala * 3) / $node->field_errezeta_prezioa['und'][0]['value'];
    }
  }
}
