<?php
/**
 * @file
 * Code for the Katakrak_search feature.
 */

include_once 'katakrak_search.features.inc';

function katakrak_search_form_apachesolr_search_custom_page_search_form_alter(&$form, $form_state) {
  if (module_exists('apachesolr_autocomplete')) {
    $element = &$form['basic']['keys'];
    apachesolr_autocomplete_do_alter($element);
  }
}

/**
 * Implements hook_block_info().
 */
function katakrak_search_block_info() {
  $blocks = array();
  $blocks['books_search_block'] = array(
    'info' => t('Search Books'),
    // Not worth caching.
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function katakrak_search_block_view($delta) {
  if ($delta == 'books_search_block') {
    $block['content'] = theme('books_search_block', array('form' => $form));
    return $block;
  }
} 