<?php
/**
 * @file
 * Code for the Katakrak_search feature.
 */

include_once 'katakrak_search.features.inc';

function katakrak_search_form_alter(&$form, &$form_state, $form_id){
  if ($form_id == 'apachesolr_panels_search_form') {
    $form['#theme'] = 'katakrak_search_book_search_form';
    if (module_exists('apachesolr_autocomplete')) {
    $element = &$form['apachesolr_panels_search_form'];
    apachesolr_autocomplete_do_alter($element);
  }
  }
}

function katakrak_search_form_apachesolr_search_custom_page_search_form_alter(&$form, $form_state) {
  
}

function katakrak_search_theme() {
  $path = drupal_get_path('module', 'katakrak_search');
  return array(
    'katakrak_search_book_search_form' => array(
      'template' => 'katakrak-search-book-search-form',
      'arguments' => array('form' => NULL),
      'render element' => 'form',
      'path' => $path . '/templates',
    ),
    'katakrak_search_books_search_block' => array(
      'template' => 'katakrak-search-book-search-block',
      'arguments' => array('form' => NULL),
      'path' => $path . '/templates',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function katakrak_search_block_info() {
  $blocks = array();
  $blocks['books_search_block'] = array(
    'info' => t('Search Books'),
    // Not worth caching.
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['katakrak_search_block'] = array(
    'info' => t('Katakrak search block'),
    // Not worth caching.
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function katakrak_search_block_view($delta) {
  if ($delta == 'books_search_block') {
    $form = drupal_get_form('books_search_form');
    $block['content'] = theme('katakrak_search_books_search_block', array('form' => $form));
    return $block;
  }
  if ($delta == 'katakrak_search_block') {
    
  }
} 

function books_search_form($form, &$form_state) {
  $form['search_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Término'),
    '#title_display' => 'invisible',
    '#attributes' => array(
      'onblur' => "if (this.value == '') {this.value = '".t('¿Qué buscas?')."';}",
      'onfocus' => "if (this.value == '".t('¿Qué buscas?')."') {this.value = '';}",
      // Prevent user from searching the default text
      'onsubmit' => "if(this.search_block_form.value=='".t('¿Qué buscas?')."'{ alert('Please enter a search'); return false; }",
      // Alternative (HTML5) placeholder attribute instead of using the javascript
      'placeholder' => t('¿Qué buscas?'),
    ),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Buscar'),
  );
  if (module_exists('apachesolr_autocomplete')) {
    //apachesolr_autocomplete_do_alter($form['search_term']);
  }
  $form['#theme'] = 'katakrak_search_book_search_form';
  return $form;
}


function books_search_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'search/books/'.$form_state['values']['search_term'];
}

function template_preprocess_katakrak_search_book_search_form(&$vars) {
  if ($vars['form']['#form_id'] == 'apachesolr_panels_search_form') {
    $vars['term_element'] = 'apachesolr_panels_search_form';
    $vars['submit_element'] = 'actions';
  }
  else {
    $vars['term_element'] = 'search_term';
    $vars['submit_element'] = 'submit';
  }
}