<?php

/**
 * Implementation of hook_menu().
 */
function katakrak_cegal_menu() {
  $items = array();
  $items['admin/commerce/config/cegal'] = array(
    'title' => 'Cegal',
    'description' => 'Configuración de módulo cegal',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('katakrak_cegal_settings_form'),
    'access arguments' => array('administer site'),
  );
  return $items;
}

function katakrak_cegal_settings_form($form, &$form_state) {
  $cegal = new CegalSearch(variable_get('cegal_user', ''), variable_get('cegal_clave', ''));
  dpm($cegal->disponibilidad(9788416946402));
   $form['cegal_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Nombre de usuario de Cegal'),
    '#description' => t('Nombre de usuario en Cegal'),
    '#size' => 30,
    '#default_value' => variable_get('cegal_user', ''),
  );
  $form['cegal_clave'] = array(
    '#type' => 'textfield',
    '#title' => t('Contraseña'),
    '#description' => t('Contraseña en Cegal'),
    '#size' => 30,
    '#default_value' => variable_get('cegal_clave', ''),
  );
  foreach (variable_get('distribuidores_confianza', array()) as $key => $value) {
    $form['distri_'.$key] = array(
      '#type' => 'fieldset',
      '#title' => $value['name'],
    );
    $form['distri_'.$key][$key.'_sinli_id'] = array(
      '#type' => 'textfield',
      '#title' => t('Id de sinli'),
      '#description' => 'Deja este campo vacio para eliminar el distribuidor',
      '#default_value' => $key,
    );
    $form['distri_'.$key][$key.'_name'] = array(
      '#type' => 'textfield',
      '#title' => t('Nombre del distribuidor'),
      '#default_value' => $value['name'],
    );
    $form['distri_'.$key][$key.'_plazo'] = array(
      '#type' => 'select',
      '#title' => t('Plazo estimado'),
      '#options' => array(
        '0' => '2-3 días',
        '1' => '3-4 días',
        '2' => '7 días'
      ),
      '#default_value' => $value['plazo']
    );
  }
  $form['distri_new'] = array(
      '#type' => 'fieldset',
      '#title' => "Nuevo distribuidor",
    );
    $form['distri_new']['sinli_id'] = array(
      '#type' => 'textfield',
      '#title' => t('Id de sinli'),
      '#default_value' => '',
    );
    $form['distri_new']['name'] = array(
      '#type' => 'textfield',
      '#title' => t('Nombre del distribuidor'),
      '#default_value' => '',
    );
    $form['distri_new']['plazo'] = array(
      '#type' => 'select',
      '#title' => t('Plazo estimado'),
      '#options' => array(
        '0' => '2-3 días',
        '1' => '3-4 días',
        '2' => '7 días'
      ),
      '#default_value' => 0
    );
    
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'enviar'
     );
  return $form;
}

function katakrak_cegal_settings_form_submit($form, &$form_state) {
  variable_set('cegal_user', $form_state['input']['cegal_user']);variable_set('cegal_clave', $form_state['input']['cegal_clave']);
  $distribuidores = variable_get('distribuidores_confianza', array());
  
  foreach($distribuidores as $key => $distri) {
    if (empty($form_state['values'][$key.'_sinli_id'])) {//Si vacias el id se borra el distribuidor
      unset($distribuidores[$key]);
    }
    elseif ($form_state['values'][$key.'_sinli_id'] != $key) {//Si ha cambiado el id de sinli
      unset($distribuidores[$key]);
      $distribuidores[$form_state['values'][$key.'_sinli_id']] = array(
        'sinli_id' => $form_state['values'][$key.'sinli_id'],
        'name' => $form_state['values'][$key.'_name'],
        'plazo' => $form_state['values'][$key.'_plazo'],
      );
    }
    else {//Si es igual lo actualizas
      $distribuidores[$form_state['values'][$key.'_sinli_id']] = array(
        'sinli_id' => $form_state['values'][$key.'sinli_id'],
        'name' => $form_state['values'][$key.'_name'],
        'plazo' => $form_state['values'][$key.'_plazo'],
      );
    }
      
  }
  
  if (!empty($form_state['input']['sinli_id'])) {
    $distribuidores[$form_state['values']['sinli_id']] = array(
      'sinli_id' => $form_state['values']['sinli_id'],
      'name' => $form_state['values']['name'],
      'plazo' => $form_state['values']['plazo'],
    );
  }
  variable_set('distribuidores_confianza', $distribuidores);
}