<?php
/**
 * @file
 * Code for the Katakrak boletin feature.
 */

include_once 'katakrak_boletin.features.inc';


function katakrak_boletin_mail_alter(&$message) {
  if ($message['module'] == 'simplenews') {
    $message['headers']['Content-Type'] = 'text/html';
    $message['headers']['Errors-To'] = 'rebotes@katakrak.net';
    $message['headers']['Return-Path'] = 'rebotes@katakrak.net';

  }
}

function katakrak_boletin_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'boletin' && $view_mode == 'full') {
    global $language;
    if ($node->content['field_boletin_eventos']){
      $header = array(
        t('Title'),
        t('Date'),
      );
      $table = array();
      foreach ($node->content['field_boletin_eventos']['#items'] as $rel) { 
        $event = $rel['node'];
        if ($event->tnid) {
          $translations = translation_node_get_translations($event->tnid);
          $event = node_load($translations[$language->language]->nid);
        }
        $table[] = array(
          l($event->title, 'node/'.$event->nid),
          format_date($event->field_event_date['und'][0]['value'], 'custom', 'd/m/Y - H:i')
        );
      }
      $node->event_table = theme('table', array('header' => $header, 'rows' => $table, 'caption' => t('Events'), 'attributes' => array('class' => array('table'))));
    }
  }
}