<?php
/**
 * @file
 * Code for the Katakrak boletin feature.
 */

include_once 'katakrak_boletin.features.inc';


function katakrak_boletin_mail_alter(&$message) {
  if ($message['module'] == 'simplenews') {
    $message['headers']['Content-Type'] = 'text/html';
    $message['headers']['Errors-To'] = 'rebotes@katakrak.net';
    $message['headers']['Return-Path'] = 'rebotes@katakrak.net';

  }
}

function katakrak_boletin_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'boletin' && $view_mode == 'full') {
    global $language;
    if ($node->content['field_boletin_eventos']){
      $header = array(
        t('Title'),
        t('Date'),
      );
      $table = array();
      foreach ($node->content['field_boletin_eventos']['#items'] as $rel) { 
        $event = $rel['node'];
        if ($event->tnid) {
          $translations = translation_node_get_translations($event->tnid);
          $event = node_load($translations[$language->language]->nid);
        }
        $table[] = array(
          l($event->title, 'node/'.$event->nid),
          format_date($event->field_event_date['und'][0]['value'], 'custom', 'd/m/Y - H:i')
        );
      }
      $node->event_table = theme('table', array('header' => $header, 'rows' => $table, 'caption' => t('Events'), 'attributes' => array('class' => array('table'))));
    }
  }
}


function katakrak_boletin_menu() {
  $items['node/%node/boletin'] = array(
    'title' => 'Boletin',
    'page callback' => 'katakrak_boletin_codigo',
    'page arguments' => array(1),
    'access callback' => 'katakrak_boletin_access_node_info',
    'access arguments' => array('access dilve information', 1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 100,
  );
  $items['node/%node/boletin_preview'] = array(
    'title' => 'Boletin preview',
    'page callback' => 'katakrak_boletin_preview',
    'page arguments' => array(1),
    'access callback' => 'katakrak_boletin_access_node_info',
    'access arguments' => array('access dilve information', 1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 100,
  );
  return $items;
}


function katakrak_boletin_access_node_info($perm, $node) {
  if (user_access($perm) && $node->type == 'boletin')
    return TRUE;
  return FALSE;
}

function katakrak_boletin_theme() {  
  $path = drupal_get_path('module', 'katakrak_boletin');
  return array(
    'boletin_codigo' => array(
      'template' => 'boletin-inline',
      'arguments' => array('node' => NULL),
      'path' => $path . '/templates',
    ),
    'boletin_preview' => array(
      'template' => 'boletin-preview',
      'arguments' => array('node' => NULL),
      'path' => $path . '/templates',
    ),
  );
}

function katakrak_boletin_codigo($node) {
  return check_plain(theme('boletin_codigo', array('node' => $node)));
}

function katakrak_boletin_preview($node) {
  print theme('boletin_preview', array('node' => $node));
  exit();
}


function katakrak_boletin_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'mailchimp_signup_subscribe_block_recibe_nuestro_boletin_semanal_form') {
//    $form['mergevars']['#prefix'] .= '<div class="row"><div class="col-lg-8  col-lg-offset-2">';
//    $form['mergevars']['#suffix'] .= '</div></div>';
    $form['actions']['submit']['#value'] = t('Suscríbeme!'); 
    foreach (array('EMAIL', 'FNAME', 'LNAME') as $value) {
      $form['mergevars'][$value]['#attributes']['placeholder'] = t($form['mergevars'][$value]['#title']);
      unset($form['mergevars'][$value]['#title']);
    }
  }
}
