<?php

/**
 * @file
 * Code for the Katakrak NNCC feature.
 */

include_once 'katakrak_nncc.features.inc';

/**
 * Implements hook_block_info().
 */

 function katakrak_nncc_block_info() {
  $blocks = array();
  $blocks['nncc_page_hero'] = array(
    'info' => t('Bloque principal página del centro de estudios'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['nncc_page_highlight'] = array(
    'info' => t('Bloque con cuatro items destacados nncc'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['katakrak_nncc_nav_submenu'] = array(
    'info' => t('Submenu nncc'),
    'cache' => DRUPAL_CACHE_PER_PAGE
  );
  $blocks['nncc_intervinientes_nav_secunday'] = array(
    'info' => t('Submenu nncc intervinientes'),
    'cache' => DRUPAL_CACHE_PER_PAGE
  );
  $blocks['nncc_filter_intervinientes'] = array(
    'info' => t('Filter intervinientes'),
    'cache' => DRUPAL_CACHE_PER_PAGE
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function katakrak_nncc_block_view($delta) {
  switch($delta) {
    case 'nncc_page_hero':
      $block['content'] = theme('katakrak_nncc_page_hero');
      break;
    case 'nncc_page_highlight':
      $block['content'] = theme('katakrak_nncc_page_highlight');
      break;
    case 'katakrak_nncc_nav_submenu':
      $links = array(
        l(t('Acerca de los Ciclos'), 'ciclos'),
        l(t('Catálogo'), 'nncc/catalogo'),
        l(t('Autoras'), 'nncc/autores'),
        l(t('En los medios'), 'nncc/medios'),
        l(t('Distribución'), 'nncc/distribucion'),
      );
      $block['content'] = theme("katakrak_navbar_submenu", array('links' => $links));
      break;
    case 'nncc_intervinientes_nav_secunday':
      $links = array(
        l(t('Autoras/es'),'nncc/intervinientes'),
        //l(t('Traductoras/es'), 'editorial/traductores')
      );
      $block['content'] = theme('katakrak_nav_secundary', array('links' => $links));
      break;
    case 'nncc_filter_intervinientes':
      drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.min.js', 'external');
      drupal_add_js(drupal_get_path('module', 'katakrak_nncc').'/katakrak_nncc.js');
      $block['content'] = theme('nncc_filter_intervinientes');
      break;
  }
  return $block;
}

/**
 * Implements hook_menu
 */

 function katakrak_nncc_menu() {
  $items['ciclos'] = array(
    'title' => 'Ciclos',
    'page callback' => 'theme',
    'page arguments' => array('katakrak_nncc_landing'),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 100,
  );

  return $items;
}

function katakrak_nncc_theme() {
	$path = drupal_get_path('module', 'katakrak_nncc');
  return array(
    'katakrak_nncc_landing' => array(
      'template' => 'katakrak-nncc-landing',
      'path' => $path . '/templates',
    ),
    'katakrak_nncc_page_hero' => array(
      'template' => 'katakrak-nncc-page-hero',
      'path' => $path . '/templates',
    ),
    'katakrak_nncc_page_highlight' => array(
      'template' => 'katakrak-nncc-page-highlight',
      'path' => $path . '/templates',
    ),
  );
}


function katakrak_nncc_access_node_info($node) {
	if ($node->type == "ciclo")
		return true;
}

/**
 *
 * @param type $nodes
 * @param type $types
 */


function katakrak_nncc_node_view($node, $view_mode) {
  if ($node->type == 'ciclo' && $view_mode == 'full')
    drupal_add_js(drupal_get_path('module', 'katakrak_nncc').'/katakrak_nncc.js');
}