<?php

/**
 * @file
 * Code for the Katakrak NNCC feature.
 */

include_once 'katakrak_nncc.features.inc';

/**
 * Implements hook_block_info().
 */

 function katakrak_nncc_block_info() {
  $blocks = array();
  $blocks['nncc_page_hero'] = array(
    'info' => t('Bloque principal página del centro de estudios'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['nncc_page_highlight'] = array(
    'info' => t('Bloque con cuatro items destacados nncc'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['nncc_landing'] = array(
    'info' => t('Bloque landing'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function katakrak_nncc_block_view($delta) {
  switch($delta) {
    case 'nncc_page_hero':
      $block['content'] = theme('katakrak_nncc_page_hero');
      break;
    case 'nncc_page_highlight':
      $block['content'] = theme('katakrak_nncc_page_highlight');
      break;
      case 'nncc_landing':
        $block['content'] = theme('katakrak_nncc_landing');
        break;
  }
  return $block;
}

/**
 * Implements hook_menu
 */

 function katakrak_nncc_menu() {
  $items['ciclos'] = array(
    'title' => 'Ciclos',
    'page callback' => 'theme',
    'page arguments' => array('katakrak_nncc_landing'),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 100,
  );

  return $items;
}

function katakrak_nncc_theme() {
	$path = drupal_get_path('module', 'katakrak_nncc');
  return array(
    'katakrak_nncc_landing' => array(
      'template' => 'katakrak-nncc-landing',
      'path' => $path . '/templates',
    ),
    'katakrak_nncc_page_hero' => array(
      'template' => 'katakrak-nncc-page-hero',
      'path' => $path . '/templates',
    ),
    'katakrak_nncc_page_highlight' => array(
      'template' => 'katakrak-nncc-page-highlight',
      'path' => $path . '/templates',
    ),
  );
}


function katakrak_nncc_access_node_info($node) {
	if ($node->type == "ciclo")
		return true;
}

/**
 *
 * @param type $nodes
 * @param type $types
 */


function katakrak_nncc_node_view($node, $view_mode) {
  if ($node->type == 'ciclo' && $view_mode == 'full')
    drupal_add_js(drupal_get_path('module', 'katakrak_nncc').'/katakrak_nncc.js');
}