<?php
/**
 * @file
 * Code for the Katakrak_home feature.
 */

include_once 'katakrak_home.features.inc';

/**
 * Implements hook_block_info().
 */
function katakrak_home_block_info() {
  $blocks = array();  
  $blocks['katakrak_home_libreria'] = array(
    'info' => t('Bloque de librería en la portada'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['katakrak_home_espacio'] = array(
    'info' => t('Bloque "Ven a Katakrak" de la home'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['katakrak_home_editorial'] = array(
    'info' => t('Bloque "Editorial" de la home'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['katakrak_home_kantina'] = array(
    'info' => t('Bloque "Kantina" de la home'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['katakrak_home_agenda'] = array(
    'info' => t('Bloque "Agenda" de la home'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['katakrak_home_banner'] = array(
    'info' => t('Bloque "Banner" de la home'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function katakrak_home_block_view($delta) {
  switch($delta) {
    case 'katakrak_home_libreria':
      $books = views_get_view_result('libros', 'book_block_home');
      $block['content'] = theme('katakrak_home_libreria', array('books' => $books));
      break;
    case 'katakrak_home_espacio':
    $block['content'] = theme('katakrak_home_espacio');
    break;
  
    case 'katakrak_home_editorial':
      $block['content'] = theme('katakrak_home_editorial');
      break;
    case 'katakrak_home_kantina':
      $block['content'] = theme('katakrak_home_kantina');
      break;
    case 'katakrak_home_agenda':
      $block['content'] = '';//theme('katakrak_home_agenda');
      break;
    case 'katakrak_home_banner':
      global $language;
      $links = language_negotiation_get_switch_links('language', drupal_get_normal_path('hazte-socix', 'es'));
      $path = $links->links[$language->language]['href'];
      $block['content'] = theme('katakrak_home_banner', array('path' => $path));
      break;
  }
  return $block;
}

/**
 * Implementation of hook_theme
 */
function katakrak_home_theme() {
  $path = drupal_get_path('module', 'katakrak_home');
  return array(
    'katakrak_home_libreria' => array(
      'template' => 'katakrak-home-libreria',
      'path' => $path . '/templates',
      'arguments' => array(
        'books' => NULL,
      )
    ),
    'katakrak_home_espacio' => array(
      'template' => 'katakrak-home-espacio',
      'path' => $path . '/templates',
    ),
    'katakrak_home_editorial' => array(
      'template' => 'katakrak-home-editorial',
      'path' => $path . '/templates',
    ),
    'katakrak_home_agenda' => array(
      'template' => 'katakrak-home-agenda',
      'path' => $path . '/templates',
    ),
    'katakrak_home_kantina' => array(
      'template' => 'katakrak-home-kantina',
      'path' => $path . '/templates',
    ),
    'katakrak_home_banner' => array(
      'template' => 'katakrak-home-banner',
      'path' => $path . '/templates',
      'arguments' => array(
        'path' => NULL,
      )
    ),
  );
}
