<?php
/**
 * @file
 * Code for the Katakrak_home feature.
 */

include_once 'katakrak_home.features.inc';

/**
 * Implements hook_block_info().
 */
function katakrak_home_block_info() {
  $blocks = array();
  $blocks['katakrak_home_promo_right'] = array(
    'info' => t('Home Promo right'),
    // Not worth caching.
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['katakrak_home_promo_bottom'] = array(
    'info' => t('Home Promo second'),
    // Not worth caching.
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function katakrak_home_block_view($delta) {
  if ($delta == 'katakrak_home_promo_right') {
    $block['content'] = theme('katakrak_home_promo_right');
    return $block;
  }
  if ($delta == 'katakrak_home_promo_bottom') {
    $block['content'] = theme('katakrak_home_promo_bottom');
    return $block;
  }
}

/**
 * Implementation of hook_theme
 */
function katakrak_home_theme() {
  $path = drupal_get_path('module', 'katakrak_home');
  return array(
    'katakrak_home_promo_right' => array(
      'template' => 'katakrak-home-promo-right',
      'path' => $path . '/templates',
    ),
    'katakrak_home_promo_bottom' => array(
      'template' => 'katakrak-home-promo-bottom',
      'path' => $path . '/templates',
    ),
  );
}

function katakrak_home_preprocess_katakrak_home_promo_right(&$vars) {
  $vars['link_agenda_icon'] = l(
    '<span class="glyphicon glyphicon-calendar fa-5x" aria-hidden="true"></span>',
    'agenda',
    array(
      'html' => TRUE,
    )
  );
  
  $vars['link_boletin_icon'] = l(
    '<span class="glyphicon glyphicon-envelope fa-5x" aria-hidden="true"></span>',
    'boletin',
    array(
      'html' => TRUE,
    )
  );
  
  $vars['link_blog_icon'] = l(
    '<span class="glyphicon glyphicon-comment fa-5x" aria-hidden="true"></span>',
    'agenda',
    array(
      'html' => TRUE,
    )
  );
}
