<?php
/**
 * @file
 * Code for the Katakrak_home feature.
 */

include_once 'katakrak_home.features.inc';

/**
 * Implements hook_block_info().
 */
function katakrak_home_block_info() {
  $blocks = array();
  $blocks['home_promo_first'] = array(
    'info' => t('Promo first'),
    // Not worth caching.
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['home_promo_second'] = array(
    'info' => t('Promo second'),
    // Not worth caching.
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['home_promo_third'] = array(
    'info' => t('Promo third'),
    // Not worth caching.
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}
