<?php
/**
 * @file
 * Code for the Katakrak itinerarios feature.
 */

include_once 'katakrak_itinerarios.features.inc';

function katakrak_itinerarios_node_load($nodes, $types) {
  if (count(array_intersect(array('itinerario'), $types))) {
    foreach($nodes as $node) {
      $paradas = array();
      foreach ($node->field_itinerario_paradas['und'] as $v) {
        $parada_entity = field_collection_item_load($v['value']);
        
        $parada = new stdClass;
        $parada->libros = array();
        foreach ($parada_entity->field_itinerario_parada_libros['und'] as $v2) {
          $libros_entity = field_collection_item_load($v2['value']);
          
          $parada_libros = array();
          foreach ($libros_entity->field_parada_libro['und'] as $nid) {
            $libro = node_load($nid['nid']);
            $libro_parada = new stdClass();
            $libro_parada->title = $libro->title;
            $libro_parada->nid = $libro->nid;
            $libro_parada->autores = $libro->autores;
            foreach ($libro->itinerarios[$node->language] as $id => $itinerario) {
              if ($id != $node->nid)
                $libro_parada->itinerarios[] = $itinerario;
            }
            
            
            if (isset($libro->field_libro_portada['und'][0]['uri'])){
              $portadas[] = array('image' => theme('image_style', array('style_name' => 'book_irakurle_taldea', 'path' => $libro->field_libro_portada['und'][0]['uri'])), 'nid' => $libro->nid);
            }
            $parada_libros['parada_libros'][] = $libro_parada;
          }
          
          $parada_libros['tipos'] = $libros_entity->field_itineraro_tipo['und'];
          $parada->libros[] = $parada_libros;
        }
        $paradas[] = $parada;
      }
      $node->paradas = $paradas;
      $portadas_tmp = array();
      $row = array();
      shuffle($portadas);
      foreach ($portadas as $k => $portada) {
        $row [] = $portada;
        if ((($k+1) % 4) == 0 ) {
          $portadas_tmp[] = $row;
          $row = array();
        }
      }
      $portadas_tmp[] = $row;
      
      $node->portadas = $portadas_tmp;
    }
  }
}

function katakrak_itinerarios_init() {
  $itinerarios = views_get_view_result('itinerarios');
  foreach($itinerarios as $itinerario) {
    $numero = $itinerario->field_field_itinerario_linea[0]['raw']['value'];
    $color = $itinerario->field_field_itinerario_color[0]['raw']['rgb'];
    if ($numero >= 10)
      $left = "18px";
    else {
      $left = "25px";
    }
    $css = ".linea-$numero .circle, .linea-$numero .itinerario-header, .linea-$numero ul.listtray li.activa{ background-color: $color} .linea-$numero .fichalinea .ficharight .listaparadastrayecto li { border-color: $color} .linea-$numero  ul.listtray li.activa{ background-color: $color} .linea-$numero .fichalinea .ficharight .listaparadastrayecto li { border-color: $color} .linea-$numero .fichalinea .ficharight .listaparadastrayecto li div.iconlistaparadatrayectos{ background-color: $color}} .linea-$numero .fichalinea .ficharight .listaparadastrayecto li div.iconlistaparadatrayectos{ background-color: $color}";
    $css .= ".circle .circle-$numero:before {
    content: \"$numero\";
    display: block;
    text-align: center;
    padding-top: 13px;
    color: #FFF;
    font-weight: bold;
    font-size: 40px;
    }
    
    ";
    $css .= ".linea-$numero .bubble:before { border-color: transparent $color } .linea-$numero .bubble {border-color: $color}";
    drupal_add_css($css, array('type' => 'inline', 'group' => CSS_THEME, 'weight' => 200));
  }
}

function katakrak_itinerarios_preprocess_node(&$vars) {
  
  if ($vars['type'] == 'itinerario') {
    $vars['ga_libro_linea'] = array(
      'utm_source' => 'itinerario_linea',
      'utm_medium' => 'web',
      'utm_campaign' => 'libros'
    );
    $vars['ga_libro_mosaico'] = array(
      'utm_source' => 'itinerario_mosaico',
      'utm_medium' => 'web',
      'utm_campaign' => 'libros'
    );
     
    
  }
}