<?php
/**
 * @file
 * Code for the Katakrak_Kantina feature.
 */

include_once 'katakrak_kantina.features.inc';

/**
 * Implement hook_query alter
 * @param type $query
 */
function katakrak_kantina_query_alter($query) {
   if ($query->hasTag('node_export_features')) {
     $query->condition('n.type', 'page');
   }
}

/**
 * Implements hook_menu
 * @return type
 */
function katakrak_kantina_menu() {
  $items['cantina']  = array(
    'title' => 'cantina',
    'page callback' => 'theme',
    'page arguments' => array('katakrak_kantina_landing'),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 100,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function katakrak_kantina_block_info() {
  $blocks = array();
  $blocks['kantina_page_hero'] = array(
    'info' => t('Bloque principal página kantina'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['kantina_page_highlight'] = array(
    'info' => t('Bloque con cuatro items destacados kantina'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['kantina_page_carousel'] = array(
    'info' => t('Bloque con carrusel en katina'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['katakrak_kantina_nav_submenu'] = array(
    'info' => t('Submenu kantina'),
    'cache' => DRUPAL_CACHE_GLOBAL
  );  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function katakrak_kantina_block_view($delta) {
  switch ($delta) {
    case 'kantina_page_hero':
      $block['content'] = theme('katakrak_kantina_page_hero');
      break;
    case 'kantina_page_highlight':
      $block['content'] = theme('katakrak_kantina_page_highlight');
      break;
    case 'kantina_page_carousel':
      $block['content'] = theme('katakrak_kantina_page_carousel');
      break;
    case 'katakrak_kantina_nav_submenu':
      $links = array(
        l(t('Menú'), 'editorial/autores'),
        l(t('Caterings'), 'editorial'),
        l(t('Nuestros productores'), 'cantina/productores'),
      );
      $block['content'] = theme("katakrak_navbar_submenu", array('links' => $links));
      break;
  }
  return $block;
}

/**
 * Implementation of hook_theme
 */
function katakrak_kantina_theme() {
  $path = drupal_get_path('module', 'katakrak_kantina');
  return array(
    'katakrak_kantina_page_hero' => array(
      'template' => 'katakrak-kantina-page-hero',
      'path' => $path . '/templates',
    ),
    'katakrak_kantina_page_highlight' => array(
      'template' => 'katakrak-kantina-page-highlight', 
      'path' => $path . '/templates',
    ),
    'katakrak_kantina_page_carousel' => array(
      'template' => 'katakrak-kantina-page-carousel', 
      'path' => $path . '/templates',
    ),
    'katakrak_kantina_landing' =>array(
      'template' => 'katakrak-kantina-landing', 
      'path' => $path . '/templates',
    )
  );
}

function katakrak_kantina_reserva_form($form, &$form_state) {
  $form['datos'] = array(
    '#type' => 'fieldset', 
    //'#title' => t('Datos personales'), 
    '#weight' => 0, 
    '#collapsible' => FALSE, 
  );
  $form['datos']['nombre'] = array(
    '#type' => 'textfield',
    '#title' => t('Nombre'),
    '#title_display' => 'invisible',
    '#required' => TRUE,
    '#attributes' => array(
      'placeholder' => t('Nombre')
    ),
  );
  
  $form['datos']['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#title_display' => 'invisible',
    '#required' => TRUE,
    '#size' => 60,
    '#attributes' => array(
      'placeholder' => t('E-mail')
    ),
  );
   $form['datos']['telefono'] = array(
    '#type' => 'textfield',
    '#title' => t('Teléfono'),
    '#title_display' => 'invisible',
    '#required' => TRUE,
    '#size' => 60,
    '#attributes' => array(
      'placeholder' => t('Teléfono')
    ),
  );
  $form['reserva'] = array(
    '#type' => 'fieldset', 
    //'#title' => t('Datos personales'), 
    '#weight' => 0, 
    '#collapsible' => FALSE, 
  );
  $form['reserva']['fecha'] = array(
    '#type' => 'date_popup',
    '#title' => t('Fecha y hora'),
    '#required' => TRUE,
    '#title_display' => 'invisible',
    '#date_format' => 'Y-m-d H:i',
  );
  $options = array();
  for($i = 1; $i < 31; $i++) {
    $options[$i] = $i;
  }
  $form['reserva']['comensales'] = array(
    '#type' => 'select',
    '#title' => t('Comensales'),
    '#title_display' => 'invisible',
    '#required' => TRUE,
    '#options' => $options,
    '#empty_option' => t('Comensales'),
    '#element_validate' => array('element_validate_integer_positive'),
  );
  $form['reserva']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  $form['#theme'] = 'katakrak_reserva_block';
  return $form;
}

function katakrak_kantina_form_katakrak_kantina_reserva_form_alter(&$form, &$form_state, $form_id) {
  $form['#after_build'][] = 'katakrak_kantina_form_reserva_after_build';
  
}

function katakrak_kantina_form_reserva_after_build($form, &$form_state){
  $form['reserva']['fecha']['date']['#description'] = '';
  $form['reserva']['fecha']['date']['#attributes']['placeholder'] = t('Fecha');
  $form['reserva']['fecha']['date']['#title_display'] = 'invisible';
  $form['reserva']['fecha']['time']['#description'] = '';
  $form['reserva']['fecha']['time']['#attributes']['placeholder'] = t('Hora');
  $form['reserva']['fecha']['time']['#title_display'] = 'invisible';
  return $form;
}

function katakrak_kantina_reserva_form_validate($form, $form_state) {
  $fecha = strtotime($form_state['values']['fecha']);
  if ($fecha < time()) {
    form_set_error('reserva][fecha', t('No puedes hacer una reserva en el pasado ;)'));
  }
  elseif (date('D', $fecha) == 'Sun') {
    form_set_error('reserva][fecha][date', t('Katakrak está cerrado los domingos'));
  }
  else {
    
  }
  
}
function katakrak_kantina_reserva_form_submit($form, &$form_state) {
}

/**
* Implements hook_mollom_form_list().
*/
function katakrak_kantina_mollom_form_list() {
  $forms['katakrak_kantina_reserva_form'] = array(
    'title' => t('Reserva form'),
  );
  return $forms;
}
/**
* Implements hook_mollom_form_info().
*/
function katakrak_kantina_mollom_form_info($form_id) {
  switch ($form_id) {
    case 'katakrak_kantina_reserva_form':
      $form_info = array(
        'mode' => MOLLOM_MODE_CAPTCHA,   
      );
      return $form_info;
  }
}

function katakrak_kantina_preprocess_katakrak_kantina_page_header(&$vars) {
  $vars['logo'] = l(theme('image', array('path' => drupal_get_path('theme', 'coworker'). '/images/kantina/kantina.jpg')), 'cantina', array('html' => TRUE));
  $dedia_imagen = theme('image', array('path' => drupal_get_path('theme', 'coworker'). '/images/kantina/dedia.jpg'));
  $denoche_imagen = theme('image', array('path' => drupal_get_path('theme', 'coworker'). '/images/kantina/denoche.jpg'));
  $blog_imagen = theme('image', array('path' => drupal_get_path('theme', 'coworker'). '/images/kantina/kantina_blog.jpg'));
  if ($vars['lang'] == 'es') {
    $vars['link_dedia'] = l($dedia_imagen.'<h3>De día</h3>', 'node/44194', array('html' => TRUE));
    $vars['link_denoche'] = l($denoche_imagen.'<h3>De noche</h3>', 'cantina/denoche', array('html' => TRUE));
    $vars['link_blog'] = l($blog_imagen.'<h3>Blog</h3>', 'cantina/blog', array('html' => TRUE));
  }
  elseif ($vars['lang'] == 'eu') {
    $vars['link_dedia'] = l($dedia_imagen.'<h3>Egunez</h3>', 'node/44194', array('html' => TRUE));
    $vars['link_denoche'] = l($denoche_imagen.'<h3>Gauez</h3>', 'node/2222', array('html' => TRUE));
    $vars['link_blog'] = l($blog_imagen.'<h3>Blog</h3>', 'cantina/blog', array('html' => TRUE));
  }
}

function katakrak_kantina_preprocess_katakrak_kantina_menu_page(&$vars) {
    global $language;
    $node = node_load(44194);
    $translations = translation_node_get_translations($node->tnid);
    $vars['node'] = node_load($translations[$language->language]->nid);
}