<?php
/**
 * @file
 * Code for the Katakrak_Kantina feature.
 */

include_once 'katakrak_kantina.features.inc';

/**
 * Implement hook_query alter
 * @param type $query
 */
function katakrak_kantina_query_alter($query) {
   if ($query->hasTag('node_export_features')) {
     $query->condition('n.type', 'page');
   }
}

/**
 * Implements hook_block_info().
 */
function katakrak_kantina_block_info() {
  $blocks = array();
  $blocks['katakrak_reserva_block'] = array(
    'info' => t('Reserva block'),
    // Not worth caching.
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['katakrak_kantina_page_header'] = array(
    'info' => t('Header cantina'),
    // Not worth caching.
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function katakrak_kantina_block_view($delta) {
  global $language;
  
  if ($delta == 'katakrak_reserva_block') {
    $block['title'] = t('Reserva sitio para comer');
    $block['content'] = drupal_get_form('katakrak_kantina_reserva_form');
    return $block;
  }
  if ($delta == 'katakrak_kantina_page_header') {
        $block['content'] = theme('katakrak_kantina_page_header', array('lang' => $language->language));
    return $block;
  }
}

/**
 * Implementation of hook_theme
 */
function katakrak_kantina_theme() {
  $path = drupal_get_path('module', 'katakrak_kantina');
  return array(
    'katakrak_kantina_page_header' => array(
      'template' => 'katakrak-kantina-page-header',
      'arguments' => array(
        'lang' => NULL,
      ),
      'path' => $path . '/templates',
    ),
  );
}

function katakrak_kantina_reserva_form($form, &$form_state) {
  $form['nombre'] = array(
    '#type' => 'textfield',
    '#title' => t('Nombre'),
    '#description' => t('Nombre de la reserva'),
    '#attributes' => array(
      'placeholder' => t('Nombre')
    ),
  );
  $form['comensales'] = array(
    '#type' => 'textfield',
    '#title' => t('Número de comensales'),
    '#attributes' => array(
      'placeholder' => 2
    ),
  );
  $form['date'] = array(
    '#type' => 'date_popup',
    '#title' => t('Fecha y hora'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}


function katakrak_kantina_reserva_form_submit($form, &$form_state) {
}

function katakrak_kantina_preprocess_katakrak_kantina_page_header(&$vars) {
  $vars['logo'] = l(theme('image', array('path' => drupal_get_path('theme', 'coworker'). '/images/kantina/kantina.jpg')), 'cantina', array('html' => TRUE));
  if ($vars['lang'] == 'es') {
    $vars['link_dedia'] = l('De día', 'node/2222', array('attributes' => array('class' => 'dedia')));
    $vars['link_denoche'] = l('De noche', 'node/2222', array('attributes' => array('class' => 'denoche')));
    $vars['link_blog'] = l('Blog', 'cantina/blog', array('attributes' => array('class' => 'kantina_blog')));
  }
 elseif ($vars['lang'] == 'eu') {
    $vars['menu_dia_path'] = 'node/44195';
  }
}