<?php
/**
 * @file
 * Code for the Katakrak_Kantina feature.
 */

include_once 'katakrak_kantina.features.inc';

/**
 * Implement hook_query alter
 * @param type $query
 */
function katakrak_kantina_query_alter($query) {
   if ($query->hasTag('node_export_features')) {
     $query->condition('n.type', 'page');
   }
}



function katakrak_kantina_menu() {
  $items = array();
  $items['cantina/denoche'] = array(
    'title' => 'De noche',
    'description' => 'Dilve options',
    'page callback' => 'katakrak_kantina_denoche_page',
    'access callback' => TRUE,
  );
  return $items;
}

function katakrak_kantina_denoche_page() {
  return theme('katakrak_kantina_denoche_page');
}


/**
 * Implements hook_block_info().
 */
function katakrak_kantina_block_info() {
  $blocks = array();
  $blocks['katakrak_reserva_block'] = array(
    'info' => t('Reserva block'),
    // Not worth caching.
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['katakrak_kantina_page_header'] = array(
    'info' => t('Header cantina'),
    // Not worth caching.
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function katakrak_kantina_block_view($delta) {
  global $language;
  
  if ($delta == 'katakrak_reserva_block') {
    $block['title'] = t('Reservas');
    $block['content'] = drupal_get_form('katakrak_kantina_reserva_form');
    return $block;
  }
  if ($delta == 'katakrak_kantina_page_header') {
        $block['content'] = theme('katakrak_kantina_page_header', array('lang' => $language->language));
    return $block;
  }
}

/**
 * Implementation of hook_theme
 */
function katakrak_kantina_theme() {
  $path = drupal_get_path('module', 'katakrak_kantina');
  return array(
    'katakrak_kantina_page_header' => array(
      'template' => 'katakrak-kantina-page-header',
      'arguments' => array(
        'lang' => NULL,
      ),
      'path' => $path . '/templates',
    ),
    'katakrak_kantina_denoche_page' => array(
      'template' => 'katakrak-kantina-denoche-page',
      'path' => $path . '/templates',
    ),
  );
}

function katakrak_kantina_reserva_form($form, &$form_state) {
  $form['nombre'] = array(
    '#type' => 'textfield',
    '#title' => t('Nombre'),
    '#description' => 'Un nombre para que apuntemos la reserva',
    '#title_display' => 'invisible',
    '#attributes' => array(
      'placeholder' => t('Nombre')
    ),
  );
  $form['comensales'] = array(
    '#type' => 'textfield',
    '#title' => t('Comensales'),
    '#description' => t('¿Cúantas sois para comer?'),
    '#title_display' => 'invisible',
    '#size' => 60,
    '#attributes' => array(
      'placeholder' => t('Comensales')
    ),
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#title_display' => 'invisible',
    '#size' => 60,
    '#attributes' => array(
      'placeholder' => t('E-mail')
    ),
  );
  $form['date'] = array(
  '#type' => 'date_popup',
  '#title' => t('Fecha y hora'),
  '#title_display' => 'invisible',
  '#date_format' => 'Y-m-d H:i',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}


function katakrak_kantina_reserva_form_submit($form, &$form_state) {
}

function katakrak_kantina_preprocess_katakrak_kantina_page_header(&$vars) {
  $vars['logo'] = l(theme('image', array('path' => drupal_get_path('theme', 'coworker'). '/images/kantina/kantina.jpg')), 'cantina', array('html' => TRUE));
  $dedia_imagen = theme('image', array('path' => drupal_get_path('theme', 'coworker'). '/images/kantina/dedia.jpg'));
  $denoche_imagen = theme('image', array('path' => drupal_get_path('theme', 'coworker'). '/images/kantina/denoche.jpg'));
  $blog_imagen = theme('image', array('path' => drupal_get_path('theme', 'coworker'). '/images/kantina/kantina_blog.jpg'));
  if ($vars['lang'] == 'es') {
    $vars['link_dedia'] = l($dedia_imagen.'<h3>De día</h3>', 'node/44194', array('html' => TRUE));
    $vars['link_denoche'] = l($denoche_imagen.'<h3>De noche</h3>', 'cantina/denoche', array('html' => TRUE));
    $vars['link_blog'] = l($blog_imagen.'<h3>Blog</h3>', 'cantina/blog', array('html' => TRUE));
  }
  elseif ($vars['lang'] == 'eu') {
    $vars['link_dedia'] = l($dedia_imagen.'<h3>Egunez</h3>', 'node/44194', array('html' => TRUE));
    $vars['link_denoche'] = l($denoche_imagen.'<h3>Gauez</h3>', 'node/2222', array('html' => TRUE));
    $vars['link_blog'] = l($blog_imagen.'<h3>Blog</h3>', 'cantina/blog', array('html' => TRUE));
  }
}