<?php
/**
 * @file
 * Code for the Potemkin feature.
 */

include_once 'katakrak_potemkin.features.inc';

/**
 * Implementation of hook_menu().
 */
function katakrak_potemkin_menu() {
  $items = array();
  $items['admin/config/potemkin'] = array(
    'title' => 'Import peliculas',
    'description' => 'Carga inicial del fichero de potemkin.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('potemkin_first_import_form'),
    'access callback' => 'user_access',
    'access arguments' => array('geslib_content import'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function potemkin_first_import_form($form, &$form_state) {
  $form['file'] = array(
    '#name' => 'files[]',
    '#type' => 'file',
    '#title' => t('Choose a file'),
    '#title_display' => 'invisible',
    '#size' => 22,
    '#theme_wrappers' => array(),
    '#weight' => -10,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',  
  );
  return $form;
}

function potemkin_first_import_form_validate($form, &$form_state) {
  $file = file_save_upload(0, array('file_validate_extensions' => array('csv')));
  if ($file) {
    $form_state['values']['file']['file'] = $file;
  }
  else {
    form_set_error('file', t('No file was uploaded.'));
  }
}


function potemkin_first_import_form_submit($form, &$form_state) {
  $file_path = '/tmp/'.file_uri_target($form_state['values']['file']['file']->uri);
  $file = fopen($file_path, 'r');
  $i = 0;
  while (fgetcsv($file, 0, ',', '"')) {
    $i++;
  }
  $batch = array(
    'title' => t('Cargando información de Potemkin'),
    'operations' => array(
      array('potemkin_process_items', array($file_path, $i)),
    ),
    'finished' => 'potemkin_import_process_finish',
  );
  
  batch_set($batch);
}

function potemkin_process_items($file_path, $max, &$context) {
  if (!isset($context['sandbox']['progress'])) {
    $context['sandbox']['file'] = fopen($file_path, 'r');
    $header = fgetcsv($context['sandbox']['file'], 0, ',', '"');
    foreach ($header as $k =>$v) {
      $context['sandbox']['header'][$k] = strtolower(str_replace(' ', '_', $v));
    }
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['max'] = $max;
  }
  $header = $context['sandbox']['header'];
  $file = $context['sandbox']['file']; 
  $limit = 100;
  $i = 0;
  $items = array();
  while($i < $limit && ($line = fgetcsv($file, 0, ',', '"')) !== FALSE) {
    foreach ($line as $k => $v) {
      $items[$i][$header[$k]] = $v;
    }
    $i++;
  }
  
  
  $context['sandbox']['progress'] += $i;  
  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}