<?php
/**
 * @file
 * Code for the Potemkin feature.
 */

include_once 'katakrak_potemkin.features.inc';

/**
 * Implementation of hook_menu().
 */
function katakrak_potemkin_menu() {
  $items = array();
  $items['admin/config/potemkin'] = array(
    'title' => 'Import peliculas',
    'description' => 'Carga inicial del fichero de potemkin.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('potemkin_first_import_form'),
    'access callback' => 'user_access',
    'access arguments' => array('geslib_content import'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function potemkin_first_import_form($form, &$form_state) {
  $potemkin_dir = DRUPAL_ROOT.'/'.variable_get('potemkin_directory', 'sites/default/files/potemkin');
  if (!file_exists($potemkin_dir)) {
    mkdir($potemkin_dir);
  }
  $files = scandir($potemkin_dir);
  foreach ($files as $key => $value) {
    if (strpos($value, '.') !== 0 AND $value != '..'){
      $options[$potemkin_dir.'/'.$value] = $value;
    }
  }
  $form['potemkin_file'] = array(
    '#type' => 'select',
    '#title' => 'Potemkin File',
    '#options' => $options,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',  
  );
  return $form;
}


function potemkin_first_import_form_submit($form, &$form_state) {
  $file_path = $form_state['values']['potemkin_file'];
  $file = fopen($file_path, 'r');
  $items = array();
  $i = 0;
  $header_tmp = fgetcsv($file, 0, ',', '"');
  foreach ($header_tmp as $k =>$v) {
      $header[$k] = strtolower(str_replace(' ', '_', $v));
  }
  while ($line = fgetcsv($file, 0, ',', '"')) {
    foreach ($line as $k => $v) {
      $items[$i][$header[$k]] = $v;
    }
    $i++;
  }
  $batch = array(
    'title' => t('Cargando información de Potemkin'),
    'operations' => array(
      array('potemkin_process_csv', array($items)),
    ),
    'finished' => 'potemkin_import_process_finish',
  );
  batch_set($batch);
}

function potemkin_process_csv($items, &$context) {
  if (!isset($context['sandbox']['progress'])) {
    $context['sandbox']['items'] = $items;
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['max'] = count($items);
  }
  $limit = 100;
  $i = 0;
  while($i < $limit) {
    $dvd = array_shift($context['sandbox']['items']);
    potemkin_process_dvd($dvd);
    $i++;
  }
  
  $context['sandbox']['progress'] += $limit;  
  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

function potemkin_process_dvd($dvd) {
  $nid = db_select('field_data_field_dvd_id', 'd')->fields('d', array('entity_id'))->condition('field_dvd_id_value', $dvd['codigo'])->execute()->fetchCol();
  if ($nid) {
    $node = node_load($nid);
  }
  else {
    $node = new stdClass();
    $node->type = 'dvd';
    $node->status = 1;
    $node->uid = 1;
  }
    
  $node->field_dvd_id['und'][0]['value'] = $dvd['codigo'];

  $node->title = $dvd['titulo'];

  foreach (array(1,2,3,4,5,6) as $i) {
    if ($dvd['act'.$i.'pel']) {
      $term = _potemkin_get_cast($dvd['act'.$i.'pel']);
      $node->field_dvd_starring['und'][($i-1)]['tid'] = $term->tid;
    }  
  }
  
  if ($dvd['sistema'] == 'DVD')
    $node->field_dvd_formato['und'][0]['value'] = 0;
  else 
    $node->field_dvd_formato['und'][0]['value'] = 1;
  
  if ($dvd['pais']) {
    $node->field_dvd_pais['und'][0]['value'] = $dvd['pais'];
  }
  if ($dvd['duracion']) {
    $node->field_dvd_duracion['und'][0]['value'] = $dvd['duracion'];
  }
  if ($dvd['ano']) {
    $node->field_dvd_ano['und'][0]['value'] = $dvd['ano'];
  }
  if ($dvd['sinopsis']) {
    $node->field_dvd_descripcion['und'][0]['value'] = $dvd['sinopsis'];
    $node->field_dvd_descripcion['und'][0]['format'] = 'sinopsis';
  }
  
  if ($dvd['genero']) {
    $tid = db_select('field_data_field_genero_dvd_id', 'd')->fields('d', array('entity_id'))->condition('field_genero_dvd_id_value', $dvd['genero'])->execute()->fetchField();
    if ($tid) {
      $genero = taxonomy_term_load($tid);
    }
    else {
      $vocab = _potemkin_get_vocab("Género DVD");
      $genero = new stdClass();
      $genero->vid = $vocab->vid;
      $genero->name = $dvd['genero'];
      $genero->field_genero_dvd_id['und'][0]['value'] = $dvd['genero'];
      taxonomy_term_save($genero);
    }
    $node->field_dvd_genero['und'][0]['tid'] = $genero->tid;
  }
  
  if ($dvd['director']) {
    $directores = explode('&', $dvd['director']);
    foreach ($directores as $i => $value) {
      $value = trim($value);
      if ($value) {
        $term = _potemkin_get_cast($value);
        $node->field_dvd_director['und'][$i]['tid'] = $term->tid;
      }
    }
  }
  
  if ($dvd['guion']) {
    $guionistas = explode('&', $dvd['guion']);
    foreach ($guionistas as $i => $value) {
      $value = trim($value);
      if ($value) {
        $term = _potemkin_get_cast($value);
        $node->field_dvd_guion['und'][$i]['tid'] = $term->tid;
      }
    }
  }
  
  if ($dvd['musica']) {
    $musica = explode('&', $dvd['musica']);
    foreach ($musica as $i => $value) {
      $value = trim($value);
      if ($value) {
        $term = _potemkin_get_cast($value);
        $node->field_dvd_musica['und'][$i]['tid'] = $term->tid;
      }
    }
  }
  
   if ($dvd['fotografia']) {
    $fotografia = explode('&', $dvd['fotografia']);
    foreach ($fotografia as $i => $value) {
      $value = trim($value);
      if ($value) {
        $term = _potemkin_get_cast($value);
        $node->field_dvd_fotografia['und'][$i]['tid'] = $term->tid;
      }
    }
  }
  
  if ($dvd['productor']) {
    $productor = explode('&', $dvd['productor']);
    foreach ($productor as $i => $value) {
      $value = trim($value);
      if ($value) {
        $term = _potemkin_get_cast($value);
        $node->field_dvd_productor['und'][$i]['tid'] = $term->tid;
      }
    }
  }
  
  if (empty($node->field_dvd_caratula)) {
    $filename = $dvd['caratula'];
    $uri = "public://caratulas/".$filename;
    $fid = db_select('file_managed', 'f')->fields('f', array('fid'))->condition('uri', $uri)
            ->execute()->fetchCol();
    if ($fid){
      $file = file_load($fid);
    }
    else {
      $file = new stdClass();
      $file->uid = 1;
      $file->filename = $filename;
      $file->uri = $uri; 
      $file->status = 1;
      $file->timestamp = REQUEST_TIME;
      file_save($file);
    }
    
    $node->field_dvd_caratula['und'][0] = (array)$file;
    $node->field_dvd_caratula['und'][0]['title'] = $node->title;
    $node->field_dvd_caratula['und'][0]['alt'] = $node->title;
  }
  
  node_save($node);
  
}

function _potemkin_get_vocab($name) {
  foreach (taxonomy_get_vocabularies() as $vid => $vocab){
    if ($vocab->name == $name) {
      return $vocab ;
    }
  }
}

/**
 * Providing a star name, returns the taxonomy object. If it doesn't exists, creates it
 * 
 * @param type $name
 * @return The taxonomy object with the cast
 */
function _potemkin_get_cast($name) {
  $cast = taxonomy_get_term_by_name($name, 'movie_stars');
  if ($cast) {
    $term = array_pop($cast);
  }
  else {
    $vocab = _potemkin_get_vocab('Movie stars');
    $term = new stdClass;
    $term->vid = $vocab->vid;
    $term->vocabulary_machine_name = $vocab->machine_name;
    $term->name = $name;
    taxonomy_term_save($term);
  }
  return $term;
}