<?php

include_once dirname(__FILE__) . '/geslib.api.inc';
include_once dirname(__FILE__) . '/lib/InetBookSearch.php';


/**
 * Implementation of hook_menu().
 */
function geslib_menu() {
  $items = array();

  # Define import form
  $items['admin/commerce/geslib'] = array(
    'title' => 'Import Geslib File',
    'description' => 'Carga inicial del fichero de geslig.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('geslib_import_form'),
    'access callback' => 'user_access',
    'access arguments' => array('geslib_content import'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/dilve'] = array(
    'title' => 'LHA Dilve',
    'description' => 'Dilve options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lha_dilve_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}


function geslib_import_form($form, &$form_state) {
   
  $geslib_dir = DRUPAL_ROOT.'/sites/default/files/geslib';
  $files = scandir(DRUPAL_ROOT.'/sites/default/files/geslib');
  foreach ($files as $key => $value) {
    if ($value != '.' AND $value != '..'){
      $options[$geslib_dir.'/'.$value] = $value;
    }
  }
  
  $form['geslib_file'] = array(
    '#type' => 'select',
    '#title' => 'Geslib File',
    '#options' => $options,
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  $form['borrar items'] = array(
    '#type' => 'submit',
    '#value' => 'Borrar todo',
  );
  
  return $form;
}

/**
 *
 */
function lha_dilve_admin_settings() {
//  $inet = new InetBookSearch();
//  dpm($inet->search_ttl("9788496453586"));
//  dpm($inet->search_google("9788496453586"));
  $portada = drupal_http_request('http://image.casadellibro.com/libros/0/revolucion-punto-cero-9788496453784.jpg');
  file_put_contents('/tmp/9788496453784.jpg', $portada->data);
  $form['lha_dilve_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Nombre de usuario'),
    '#description' => t('Nombre de usuario en Dilve'),
    '#size' => 30,
    '#default_value' => variable_get('lha_dilve_user', ''),
  );
  $form['lha_dilve_pass'] = array(
    '#type' => 'textfield',
    '#title' => t('Contraseña'),
    '#description' => t('Contraseña en Dilve'),
    '#size' => 30,
    '#default_value' => variable_get('lha_dilve_pass', ''),
  );
  return system_settings_form($form);
}

function geslib_import_form_submit($form, &$form_state) {
 
  if ($form_state['clicked_button']['#value'] == 'Borrar todo') {
    $batch = array(
      'title' => t('Eliminando todos los elementos'),
      'operations' => array(
        array('geslib_process_delete_categories', array()),
        array('geslib_process_delete_products', array()), 
        array('geslib_process_delete_nodes', array()),
      ),
      'finished' => 'geslib_process_finish',
      'file' => drupal_get_path('module', 'geslib').'/geslib.batch.inc',
    );
    batch_set($batch);
  }
  else {
    $batch = array(
      'title' => t('Importando artículos de geslib'),
      'operations' => array(
          array('geslib_process_read_file', array($form_state['values']['geslib_file'])),
          array('geslib_process_create_publishers', array()), 
          array('geslib_process_create_categories', array() ),
          array('geslib_process_create_autores', array() ),
          array('geslib_process_create_products', array() ),
          //array('geslib_process_dilve', array() ),
      ),
      'finished' => 'geslib_process_finish',
      'file' => drupal_get_path('module', 'geslib').'/geslib.batch.inc',
    );
    batch_set($batch);
  }
}


