<?php

$plugin = array(
  'title' => t('Search layout'),
  'category' => t('Kapital'),
  'icon' => 'search-layout.png',
  'theme' => 'search-layout',
  'regions' => array(
    'facet_left' => t('Facet left'),
    'facet_right' => t('Facet right'),
    'facet_middle' => t('Facet middle'),
    'content' => t('Content'),
    'content_top' => t('Content top'),
    'facetapi_badge' => t('Facetapi Badges'),
    'search_sort' => t('Search sort'),
  ),
);