<?php
/**
 * @file
 * katakrak_editorial.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function katakrak_editorial_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_autor_nacimiento'.
  $field_bases['field_autor_nacimiento'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_autor_nacimiento',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_editorial_libro'.
  $field_bases['field_editorial_libro'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_editorial_libro',
    'indexes' => array(
      'nid' => array(
        0 => 'nid',
      ),
    ),
    'locked' => 0,
    'module' => 'node_reference',
    'settings' => array(
      'referenceable_types' => array(
        'article' => 0,
        'autor_ed' => 0,
        'blog' => 0,
        'boletin' => 0,
        'ciclo' => 0,
        'eguneko_menua' => 0,
        'event' => 0,
        'imagen' => 0,
        'itinerario' => 0,
        'libro' => 'libro',
        'libro_ed' => 0,
        'page' => 0,
        'portfolio' => 0,
        'receta' => 0,
        'simplenews' => 0,
        'sukalde_errezeta' => 0,
        'sukalde_produktua' => 0,
      ),
      'view' => array(
        'args' => array(),
        'display_name' => '',
        'view_name' => '',
      ),
    ),
    'translatable' => 0,
    'type' => 'node_reference',
  );

  // Exported field_base: 'field_libro_ed_autor'.
  $field_bases['field_libro_ed_autor'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_libro_ed_autor',
    'indexes' => array(
      'nid' => array(
        0 => 'nid',
      ),
    ),
    'locked' => 0,
    'module' => 'node_reference',
    'settings' => array(
      'referenceable_types' => array(
        'article' => 0,
        'autor_ed' => 'autor_ed',
        'blog' => 0,
        'boletin' => 0,
        'ciclo' => 0,
        'eguneko_menua' => 0,
        'event' => 0,
        'imagen' => 0,
        'itinerario' => 0,
        'libro' => 0,
        'libro_ed' => 0,
        'page' => 0,
        'portfolio' => 0,
        'receta' => 0,
        'simplenews' => 0,
        'sukalde_errezeta' => 0,
        'sukalde_produktua' => 0,
      ),
      'view' => array(
        'args' => array(),
        'display_name' => '',
        'view_name' => '',
      ),
    ),
    'translatable' => 0,
    'type' => 'node_reference',
  );

  return $field_bases;
}
