<?php

/**
 * @file
 * Code for the Katakrak User feature.
 */

include_once 'katakrak_user.features.inc';

/**
 * Implements hook_theme
 */
function katakrak_user_theme() {
  $path = drupal_get_path('module', 'katakrak_user');
  return array(
    'katakrak_user_login_form' => array(
      'template' => 'katakrak-user-login-form',
      'path' => $path . '/templates',
      'arguments' => array('form' => NULL),
      'render element' => 'form',
    ),
  );
}

function katakrak_user_permission() {
  return array(
    'view tabs' => array(
      'title' => t('View tabs in content'),
      'description' => t('Perform administration tasks for my module.'),
    ),
  );
}

/**
 * 
 */
function katakrak_user_menu_alter(&$items) {
  $items['user/login']['title callback'] = 'katakrak_user_login_title_callback';
}

/**
 * 
 * @return type
 */
function katakrak_user_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form' || $form_id == 'user_login') {
    $form['actions']['submit']['#attributes']['class'] = array('mb-3', 'mt-2');
  }
}



function katakrak_user_login_title_callback() {
  return t('Mi cuenta');
}

/**
 * Implements hook_block_info().
 */
function katakrak_user_block_info() {
  $blocks = array();
  
  $blocks['katakrak_user_login_help'] = array(
    'info' => t('Katakrak user login help'),
    // Not worth caching.
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['katakrak_user_nav_secundary'] = array(
    'info' => t('Submenu usuario'),
    'cache' => DRUPAL_CACHE_PER_PAGE
  ); 
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function katakrak_user_block_view($delta) {
  switch($delta) {
    case 'katakrak_user_login_help':
    $block['content'] = '<div class="banner-help">'.
      '<i class="far fa-question-circle"></i> '.
      t('Necesitas tu <strong>cuenta Katakrak</strong> para hacer compras, seguir tus pedidos, etc...').
      '</div>';
      break;
    case 'katakrak_user_nav_secundary':
      global $user;
      $links = array(
        l(t('Mi cuenta'), 'user/'.$user->uid.'/edit'),
        l(t('Mis pedidos'), 'user/'.$user->uid.'/orders'),
      );
      $block['content'] = theme("katakrak_navbar_submenu", array('links' => $links));
      break;
    }
    return $block;
  }