<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-3">
           <?php print render($page['footer_first']); ?>
      </div><!-- /.col -->
      <div class="col-sm-6 col-md-3">
        <?php print render($page['footer_second']); ?>
      </div><!-- /.col -->
      <div class="col-sm-6 col-md-3">
         <?php print render($page['footer_third']); ?>
      </div><!-- /.col -->
      <div class="col-sm-6 col-md-3">
        <?php print render($page['footer_fourth']); ?>     
      </div><!-- /.col -->

    </div><!-- /.row -->
  </div>
</footer>