<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-4">
           <?php print render($page['footer_first']); ?>
      </div><!-- /.col -->
      <div class="col-sm-6 col-md-4">
        <?php print render($page['footer_second']); ?>
      </div><!-- /.col -->
      <div class="col-sm-6 col-md-4">
         <?php print render($page['footer_third']); ?>
      </div><!-- /.col -->

    </div><!-- /.row -->
  </div>
</footer>