<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-4">
           <?php print render($page['footer_first']); ?>
      </div><!-- /.col -->
      <div class="col-sm-6 col-md-4">
        <?php print render($page['footer_second']); ?>
      </div><!-- /.col -->
      <div class="col-sm-6 col-md-4">
         <?php print render($page['footer_third']); ?>
      </div><!-- /.col -->

    </div><!-- /.row -->
  </div>
</footer>
<footer class="colophon">
  <div class="container">
    <a href="http://www.culturaydeporte.gob.es/" target="_blank" title="Ir a la web de Ministerio de Cultura y Deporte de España">
      <img src="/sites/all/themes/kapital/images/logo-ministerio-dglfl.jpg" alt="<?php print t('Ministerio de Cultura y Deporte de España') ?>" class="img-cultura">
    </a>
  </div>
</footer>